version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: worklogdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: thiru
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    build:
      context: ./server
    container_name: springboot_server
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/worklogdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: thiru
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  ui:
    build:
      context: ./ui
    container_name: angular_ui
    ports:
      - "8080:80"
    depends_on:
      - server

volumes:
  pgdata:
